<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-28 at 19:46:57.
 */
class yiff_viewTest extends PHPUnit_Framework_TestCase {

    /**
     * @var yiff_view
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new yiff_view;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
